### ISSUE TITLE
Cannot build example program

### ISSUE THREAD

**Issue by XiKuuKy** [fsprojects/FsLexYacc#36] opened 2015-02-13 00:24 UTC
I couldn't build the example program. It gave me an error saying that there was an unexpected ".

**Comment by brodyberg** [comment] 2015-02-13 00:35
Sorry to hear that - can you possibly reply with more of the build error? Also, what are you using to build (Visual Studio/Xamarin) and which version of F#? Thanks!

**Comment by XiKuuKy** [comment] 2015-02-13 03:46
I am using Visual Studio 2013 Pro. I am using F# 4 or 3(I don't know). The error was Error	1	Unexpected character '﻿' in implementation file	c:\Users\Simon\documents\visual studio 2013\Projects\FerLang\FerLang\Program.fs	1	1	FerLang

**Comment by brodyberg** [comment] 2015-02-13 04:07
I think you somehow got a bogus character in there at the beginning of your file. Which exact example are we talking about? Did you copy/paste from here: https://github.com/fsprojects/FsLexYacc/blob/master/tests/LexAndYaccMiniProject/Program.fs

I ran into this type of thing all the time with Xamarin recently due to the text-editor having major problems with intellisense around array literals: [| foo |]. 

Check your file right at position 1, 1 for a hidden character in VS. If you don't see anything, open the file in notepad as well and check that same location. Delete what you find and then try a rebuild.

**Comment by dsyme** [comment] 2015-05-30 23:56
Hi @XiKuuKy - is this still a problem?  If the problem is something at the start of a file then it might be a problem with Unicode Byte Order Marks?

**Comment by dsyme** [comment] 2015-05-30 23:56
I'll close this until exact further repro steps are given

**Closed by dsyme** 2015-05-30 23:56 UTC
